version: '3.3'
services:

  db_mysql:
    container_name: db_mysql
    image: mysql
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhome
      MYSQL_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    depends_on:
        db_mysql:
          condition: service_healthy
    image: phpmyadmin/phpmyadmin
    ports:
      - '9001:80'
    environment:
      PMA_HOST: db_mysql
  web:
      container_name: myhome
      image: temporalparadox/myhome:master
#      build: .
      ports:
        - '9005:8080'
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/myhome
      depends_on:
          db_mysql:
            condition: service_healthy

volumes:
  mysql-data:

